# docker-compose.yml
version: "3"

services:
  dns-server:
    image: technitium/dns-server:latest
    container_name: technitium-dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5380:5380/tcp"
    volumes:
      - ./data/dns_logs:/etc/dns/logs # <--- host folder mapped to container logs
    environment:
      - TZ=Asia/Phnom_Penh # optional: set timezone
